# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # openresty box
  config.vm.define "openresty" do |openresty|
##    openresty.vm.box = "bento/debian-7.9"
##    openresty.vm.box = "bento/debian-9.6"
	openresty.vm.box = "boxesio/stretch64"

    openresty.vm.hostname = "openresty"
	openresty.vm.network :private_network, ip: "192.168.56.110"

	openresty.vm.provider :virtualbox do |vb|
	  vb.customize [ "modifyvm", :id, "--ioapic", "on" ]
	  vb.customize [ "modifyvm", :id, "--cpus", "2" ]
	  vb.customize [ "modifyvm", :id, "--memory", "8192" ]
	end

    # fix that annoying "stdin: is not a tty"
    # see http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html
    openresty.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    openresty.vm.provision :shell, path: "bootstrap-scripts/install-openresty+realtime-extras"
  end

end
