#!/usr/bin/env bash
set -euo pipefail

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### make info messages hi-vis
info_msg () {
	echo -e '\E[37;44m'"\033[1m::::: "$1"\033[0m"
	tput sgr0
}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

# add a module into openresty build system
add_custom_nginx_module () {

	### get module info from function params

	MODULE_GITHUB_USER="$1"
	MODULE_GITHUB_PROJECT="$2"
	OPENRESTY_WORKING_DIRECTORY="$3"

	### get info for specified module

	info_msg "===== getting github project info for ${MODULE_GITHUB_USER}/${MODULE_GITHUB_PROJECT} latest version"
	MODULE_GITHUB_INFO=$(curl https://api.github.com/repos/${MODULE_GITHUB_USER}/${MODULE_GITHUB_PROJECT}/tags 2>/dev/null)
	MODULE_GITHUB_VERSION=$(echo "${MODULE_GITHUB_INFO}"| jq -r '.[0].name')
	MODULE_GITHUB_TARBALL_URL=$(echo "${MODULE_GITHUB_INFO}"| jq -r '.[0].tarball_url')
	MODULE_GITHUB_COMMIT_STRING=$(echo "${MODULE_GITHUB_INFO}" | jq -r '.[0].commit.sha[0:7]')
	MODULE_GITHUB_PACKAGE_NAME="${MODULE_GITHUB_USER}-${MODULE_GITHUB_PROJECT}-${MODULE_GITHUB_COMMIT_STRING}"

	### add specified module to the openresty build system

	ESCAPED_MODULE_GITHUB_TARBALL_URL=$(echo "${MODULE_GITHUB_TARBALL_URL}" | sed 's/\//\\\//g')
	OPENRESTY_MODULE_PACKAGE_NAME="${MODULE_GITHUB_PROJECT}-${MODULE_GITHUB_VERSION}"
	OPENRESTY_MODULE_TARBALL_NAME="${OPENRESTY_MODULE_PACKAGE_NAME}.tar.gz"

	info_msg "===== adding ${MODULE_GITHUB_PROJECT} to the ${OPENRESTY_GITHUB_PROJECT} 'mirror-tarballs' script"
	sed "s/\(^.* \*\.tar\.gz$\)/ver=${MODULE_GITHUB_VERSION}\n\$root\/util\/get-tarball \"${ESCAPED_MODULE_GITHUB_TARBALL_URL}\" -O \"${OPENRESTY_MODULE_TARBALL_NAME}\" || exit 1\ntar -xzf ${OPENRESTY_MODULE_TARBALL_NAME} || exit 1\nmv ${MODULE_GITHUB_PACKAGE_NAME} ${OPENRESTY_MODULE_PACKAGE_NAME} || exit 1\n\n#################################\n\n\1/g" -i ${OPENRESTY_WORKING_DIRECTORY}/util/mirror-tarballs

}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### get started

info_msg "##### setting up openresty/nginx + push-stream module #####"

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### set google DNS resolver to avoid slow-DNS-forwarding pain

info_msg "===== adding google DNS resolver inside VM"
sed \
	-e 's/^nameserver .*/nameserver 8.8.8.8/g' \
	-i /etc/resolv.conf
info_msg "----- checking for google DNS resolver"
fgrep nameserver /etc/resolv.conf

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### update OS stuff

info_msg "===== upgrading OS to latest version"
info_msg "apt-get update -y"
apt-get update -y

info_msg "apt-get upgrade -y"
apt-get upgrade -y

##### old wheezy/jessie backports stuff for debian-7.9

#	info_msg "===== getting wheezy-backports apt sources list"
#	cat >> /etc/apt/sources.list <<EOF
#	deb http://ftp.uk.debian.org/debian wheezy-backports main
#	deb-src http://ftp.uk.debian.org/debian wheezy-backports main
#	EOF
#
#	info_msg "===== updating system package list with wheezy-backports"
#	info_msg "apt-get -o Acquire::Check-Valid-Until=false update"
#	apt-get -o Acquire::Check-Valid-Until=false update
#
#	info_msg "===== getting debian keyring packages"
#	info_msg "apt-get install -y debian-keyring debian-archive-keyring"
#	apt-get install -y debian-keyring debian-archive-keyring

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### install useful stuff

info_msg "===== installing useful tools"
info_msg "apt-get install -y jq"
apt-get install -y jq

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### install openresty/nginx stuff

info_msg "===== installing openresty prerequisites"
info_msg "apt-get install -y init-system-helpers build-essential libreadline-dev libncurses5-dev libssl-dev perl make dos2unix mercurial vim"
apt-get install -y init-system-helpers build-essential libreadline-dev libncurses5-dev libssl-dev perl make dos2unix mercurial vim

info_msg "===== installing debian nginx files"
info_msg "apt-get install -y nginx-common"
apt-get install -y nginx-common

cat > ~/.vimrc <<EOF
syntax on
set ai
set ts=4
set sw=4
EOF

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### install markdown2pod

if [ -z $(which markdown2pod) ] ; then
	info_msg "===== installing markdown2pod"
	PERL_MM_USE_DEFAULT=1 perl -MCPAN -e "CPAN::Shell->notest('install', 'Markdown::Pod')"
	info_msg "checking for markdown2pod ..."
	which markdown2pod
fi

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### install maxmind db
info_msg "===== installing maxmind db library"
MAXMIND_INSTALL_PATH=/usr/share/maxmind
MAXMIND_LIB_PATH=${MAXMIND_INSTALL_PATH}/lib
MAXMIND_INC_PATH=${MAXMIND_INSTALL_PATH}/include
curl -OL https://github.com/maxmind/libmaxminddb/releases/download/1.1.2/libmaxminddb-1.1.2.tar.gz
tar xzf libmaxminddb-1.1.2.tar.gz
pushd libmaxminddb-1.1.2
./configure --prefix=${MAXMIND_INSTALL_PATH}
make
make install
info_msg "===== adding maxmind db library to ld.so.conf"
echo "${MAXMIND_LIB_PATH}" > /etc/ld.so.conf.d/libmaxminddb.conf
ldconfig -v 2>/dev/null |grep -i maxmind
popd

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### install FPM meta-packager | https://github.com/jordansissel/fpm

info_msg "===== installing fpm prerequisites"
info_msg "----- installing ruby"
info_msg "apt-get install -y ruby ruby-dev"
apt-get install -y ruby ruby-dev
info_msg "----- installing fpm"
info_msg "gem install fpm"
gem install fpm

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

# get latest PCRE library v1 branch release, to enable pcre-JIT compiler in nginx/ngx_lua

info_msg "===== installing pcre library"
PCRE_INSTALL_PATH=/usr/share/pcre
PCRE_LIB_PATH=${PCRE_INSTALL_PATH}/lib
PCRE_INC_PATH=${PCRE_INSTALL_PATH}/include
PCRE_VERSION=$(\
	curl ftp://ftp.pcre.org/pub/pcre/ 2>/dev/null \
	| awk '{print $9}' \
	| egrep '^pcre-.*bz2$' \
	| tail -1 \
	| sed 's/.tar.bz2$//g' \
	| tr -d '\n'\
)
info_msg "----- downloading PCRE library"
info_msg "curl -L -O ftp://ftp.pcre.org/pub/pcre/${PCRE_VERSION}.tar.bz2"
curl -L -O ftp://ftp.pcre.org/pub/pcre/${PCRE_VERSION}.tar.bz2
info_msg "unzipping ${PCRE_VERSION}"
tar jxf ${PCRE_VERSION}.tar.bz2
info_msg "checking for ${PCRE_VERSION}..."
ls -ld ${PCRE_VERSION}
pushd ${PCRE_VERSION}
./configure --prefix=${PCRE_INSTALL_PATH}
make
make install
info_msg "===== adding pcre library to ld.so.conf"
echo "${PCRE_INSTALL_PATH}" > /etc/ld.so.conf.d/libpcre.conf
ldconfig -v 2>/dev/null | grep -i pcre
popd

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### kick off openresty install | http://openresty.org/

OPENRESTY_GITHUB_USER='openresty'
OPENRESTY_GITHUB_PROJECT='openresty'
info_msg "===== getting github project info for ${OPENRESTY_GITHUB_USER}/${OPENRESTY_GITHUB_PROJECT} latest version"
# get all the tags
OPENRESTY_GITHUB_RESPONSE=$(curl https://api.github.com/repos/${OPENRESTY_GITHUB_USER}/${OPENRESTY_GITHUB_PROJECT}/tags 2>/dev/null)
# strip out release candidate
OPENRESTY_GITHUB_INFO=$(echo "${OPENRESTY_GITHUB_RESPONSE}"| jq -r '. - map(select(.name|endswith("rc1")))')
OPENRESTY_GITHUB_VERSION=$(echo "${OPENRESTY_GITHUB_INFO}"| jq -r '.[0].name')
OPENRESTY_GITHUB_TARBALL_URL=$(echo "${OPENRESTY_GITHUB_INFO}"| jq -r '.[0].tarball_url')
OPENRESTY_GITHUB_COMMIT_STRING=$(echo "${OPENRESTY_GITHUB_INFO}" | jq -r '.[0].commit.sha[0:7]')
OPENRESTY_GITHUB_PACKAGE_NAME="${OPENRESTY_GITHUB_USER}-${OPENRESTY_GITHUB_PROJECT}-${OPENRESTY_GITHUB_COMMIT_STRING}"

info_msg "===== retrieving ${OPENRESTY_GITHUB_USER}/${OPENRESTY_GITHUB_PROJECT} version ${OPENRESTY_GITHUB_VERSION}"
OPENRESTY_LOCAL_TARBALL_NAME=${OPENRESTY_GITHUB_PACKAGE_NAME}-${OPENRESTY_GITHUB_VERSION}.tar.gz
curl -o ${OPENRESTY_LOCAL_TARBALL_NAME} -L ${OPENRESTY_GITHUB_TARBALL_URL} 2>/dev/null

tar zxvf ${OPENRESTY_LOCAL_TARBALL_NAME}
info_msg "===== changing to ${OPENRESTY_GITHUB_USER} directory"
cd openresty-openresty-??????? #${OPENRESTY_GITHUB_PACKAGE_NAME}
ls -l

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

info_msg "adding custom modules to openresty build"

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

###	push-stream-module | https://github.com/wandenberg/nginx-push-stream-module

PUSH_STREAM_MODULE_NAME="nginx-push-stream-module"
add_custom_nginx_module "wandenberg" "${PUSH_STREAM_MODULE_NAME}" "$(pwd)"

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

###	geoip2 module | https://github.com/leev/ngx_http_geoip2_module

GEOIP2_MODULE_NAME="ngx_http_geoip2_module"
add_custom_nginx_module "leev" "${GEOIP2_MODULE_NAME}" "$(pwd)"

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### pull in openresty packages

info_msg "===== fixing simpl/simplresty- in mirror-tarballs ..."
sed \
	-e "s/^mv simpl-ngx_devel_kit/mv simplresty-ngx_devel_kit/g" \
	-i ${OPENRESTY_WORKING_DIRECTORY}/util/mirror-tarballs

info_msg "===== building ${OPENRESTY_GITHUB_PROJECT}-${OPENRESTY_GITHUB_COMMIT_STRING}/${OPENRESTY_GITHUB_VERSION} (= pre-build, pull down bundle) ..."
make -j "$(( $(cat /proc/cpuinfo | egrep ^processor | wc -l) + 1))"

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### add nginx-push-stream-module/ngx_http_geoip2_module
### into openresty configure script.
### values in key-value pairs http_k_k => http_v_v are names of github projects
### ie nginx-push-stream-module, ngx_http_geoip2_module
### super brittle, mmm

LOCAL_OPENRESTY_PACKAGE_VERSION=$(echo "${OPENRESTY_GITHUB_VERSION}" | sed -e 's/^v//g')
OPENRESTY_LOCAL_NGX_DIR="${OPENRESTY_GITHUB_PROJECT}-${LOCAL_OPENRESTY_PACKAGE_VERSION}"
info_msg "===== adding ${PUSH_STREAM_MODULE_NAME}, ${GEOIP2_MODULE_NAME} to ${OPENRESTY_LOCAL_NGX_DIR}/configure ..."
sed \
	-e "s/\(my @modules = (\)/\1\n    [http_push_stream => '${PUSH_STREAM_MODULE_NAME}'],\n    [http_geoip2 => '${GEOIP2_MODULE_NAME}'],/g" \
	-i ${OPENRESTY_LOCAL_NGX_DIR}/configure

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### patch nginx src to have a longer NGX_MAX_ERROR_STR
### so that apps can log more detailed info

NGX_MAX_ERROR_STR=8192
info_msg "===== patching nginx to have NGX_MAX_ERROR_STR = ${NGX_MAX_ERROR_STR} to have longer error log messages"
pushd ${OPENRESTY_LOCAL_NGX_DIR}/bundle/nginx-[0-9\.]*
sed "s/\(#define NGX_MAX_ERROR_STR *\)4096/\1\t${NGX_MAX_ERROR_STR}/g" -i src/core/ngx_log.h
# fix vim coloring with an errant "
info_msg "----- checking for NGX_MAX_ERROR_STR"
fgrep "define NGX_MAX_ERROR_STR" src/core/ngx_log.h
popd

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### run openresty configure script, using choice configure options from 'nginx -V' in debian nginx package
### so we can take advantage of the very lovely init script and conf/packaging work the debian folks have done

OPENRESTY_INSTALL_PREFIX=/usr/share/openresty
OPENRESTY_INSTALL_PREFIX_ESCAPED=$(echo ${OPENRESTY_INSTALL_PREFIX} | sed 's/\//\\\//g')

info_msg "===== configure-ing ${OPENRESTY_LOCAL_NGX_DIR} (with LD_LIBRARY_PATH=${MAXMIND_LIB_PATH}:${PCRE_LIB_PATH}, -I${MAXMIND_INC_PATH}:${PCRE_INC_PATH})"
cd ${OPENRESTY_LOCAL_NGX_DIR}
info_msg "[ working in $(pwd) ]"
info_msg "----- configure command: -----"
echo "./configure \\"
#echo "--with-cc-opt=\"-g -O2 -fstack-protector=strong --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -I${MAXMIND_INC_PATH} -I${PCRE_INC_PATH}\\"
echo "--with-cc-opt=\"-g -O2 -fstack-protector=strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -I${MAXMIND_INC_PATH} -I${PCRE_INC_PATH}\" \\"
echo "--with-ld-opt=\"-Wl,-z,relro -Wl,-z,now -L${MAXMIND_LIB_PATH} -lmaxminddb -L${PCRE_LIB_PATH} -lpcre\" \\"
echo "--with-luajit \\"
echo "--with-debug \\"
echo "--with-pcre=../../${PCRE_VERSION} \\"
echo "--with-pcre-jit \\"
echo "--with-pcre-conf-opt=\"--enable-unicode-properties\" \\"
echo "--with-http_dav_module \\"
echo "--prefix=${OPENRESTY_INSTALL_PREFIX} \\"
echo "--conf-path=/etc/nginx/nginx.conf \\"
echo "--http-log-path=/var/log/nginx/access.log \\"
echo "--error-log-path=/var/log/nginx/error.log \\"
echo "--lock-path=/var/lock/nginx.lock \\"
echo "--pid-path=/run/nginx.pid \\"
echo "--http-client-body-temp-path=/var/lib/nginx/body \\"
echo "--http-fastcgi-temp-path=/var/lib/nginx/fastcgi \\"
echo "--http-proxy-temp-path=/var/lib/nginx/proxy \\"
echo "--http-scgi-temp-path=/var/lib/nginx/scgi \\"
echo "--http-uwsgi-temp-path=/var/lib/nginx/uwsgi \\"
echo "--with-ipv6 \\"
echo "--with-http_v2_module \\"
echo "--with-http_ssl_module \\"
echo "--with-http_stub_status_module \\"
echo "--with-http_realip_module \\"
echo "--with-http_auth_request_module \\"
echo "--with-http_addition_module \\"
echo "--with-http_gzip_static_module \\"
echo "--with-http_sub_module"
info_msg "----- end configure command: -----"

./configure \
--with-cc-opt="-g -O2 -fstack-protector=strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -I${MAXMIND_INC_PATH} -I${PCRE_INC_PATH}" \
--with-ld-opt="-Wl,-z,relro -Wl,-z,now -Wl,-rpath,${MAXMIND_LIB_PATH}:${PCRE_LIB_PATH} -lmaxminddb -lpcre" \
--with-luajit \
--with-debug \
--with-pcre="../../${PCRE_VERSION}" \
--with-pcre-jit \
--with-pcre-conf-opt="--enable-unicode-properties" \
--with-http_dav_module \
--prefix=${OPENRESTY_INSTALL_PREFIX} \
--conf-path=/etc/nginx/nginx.conf \
--http-log-path=/var/log/nginx/access.log \
--error-log-path=/var/log/nginx/error.log \
--lock-path=/var/lock/nginx.lock \
--pid-path=/run/nginx.pid \
--http-client-body-temp-path=/var/lib/nginx/body \
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
--http-proxy-temp-path=/var/lib/nginx/proxy \
--http-scgi-temp-path=/var/lib/nginx/scgi \
--http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
--with-ipv6 \
--with-http_v2_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_realip_module \
--with-http_auth_request_module \
--with-http_addition_module \
--with-http_gzip_static_module \
--with-http_sub_module

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### build & install openresty
### - package created by FPM will be openresty_<version>+push-stream-<version>_<arch>.deb

LOCAL_OPENRESTY_PACKAGE_NAME="${OPENRESTY_GITHUB_PROJECT}-${LOCAL_OPENRESTY_PACKAGE_VERSION}+realtime-geoip2"
info_msg "===== building ${LOCAL_OPENRESTY_PACKAGE_NAME}"
make -j "$(( $(cat /proc/cpuinfo | egrep ^processor | wc -l) + 1))"

info_msg "===== installing ${LOCAL_OPENRESTY_PACKAGE_NAME}"
make install

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### set up necessary files for .deb package

# make sure nginx is symlinked to /usr/sbin for init & systemd
OPENRESTY_SBIN=${OPENRESTY_INSTALL_PREFIX}/nginx/sbin
OPENRESTY_NGINX_BINARY=${OPENRESTY_SBIN}/nginx
SYSTEM_SBIN=/usr/sbin
SYSTEM_NGINX_BINARY=${SYSTEM_SBIN}/nginx

# symlink openresty nginx binary to /usr/sbin
ln -sf ${OPENRESTY_NGINX_BINARY} ${SYSTEM_NGINX_BINARY}

# create after-install script for .deb file
# adds libmaxminddb to ld.so.conf
NGINX_ETC_DIR=${OPENRESTY_INSTALL_PREFIX}/etc
mkdir -p ${NGINX_ETC_DIR}
AFTER_INSTALL_SCRIPT=${NGINX_ETC_DIR}/after-install
cat > ${AFTER_INSTALL_SCRIPT} <<EOF
# add maxmind to ld.so.conf
echo ${MAXMIND_LIB_PATH} > /etc/ld.so.conf.d/libmaxminddb.conf
echo ${PCRE_LIB_PATH} > /etc/ld.so.conf.d/libpcre.conf
ldconfig -v 2>/dev/null | grep -i maxmind
ldconfig -v 2>/dev/null | grep -i pcre
EOF

# make sure OPM site directories get included
for dir in lualib manifest pod ; do
	touch ${OPENRESTY_INSTALL_PREFIX}/site/$dir/.ensure-dir-is-packaged
done

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### build the .deb package

FPM_OPENRESTY_PACKAGE_VERSION=${LOCAL_OPENRESTY_PACKAGE_VERSION}+realtime-geoip2-vbox-debian-9
FPM_OPENRESTY_FILE_PATHS="${MAXMIND_INSTALL_PATH} ${PCRE_INSTALL_PATH} ${SYSTEM_NGINX_BINARY} ${OPENRESTY_INSTALL_PREFIX}"
info_msg "===== building .deb package for ${OPENRESTY_GITHUB_USER}/${FPM_OPENRESTY_PACKAGE_VERSION}"
info_msg "fpm -s dir -t deb -d 'nginx-common' -n ${OPENRESTY_GITHUB_USER} -v ${FPM_OPENRESTY_PACKAGE_VERSION} --after-install ${AFTER_INSTALL_SCRIPT} ${FPM_OPENRESTY_FILE_PATHS}"
fpm -s dir -t deb -d 'nginx-common' -n ${OPENRESTY_GITHUB_USER} -v ${FPM_OPENRESTY_PACKAGE_VERSION} --after-install ${AFTER_INSTALL_SCRIPT} ${FPM_OPENRESTY_FILE_PATHS}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### get on the home straight

info_msg "===== moving .deb package to /vagrant"
mv ${OPENRESTY_GITHUB_USER}_*.deb /vagrant
info_msg "ls -l /vagrant"
ls -l /vagrant

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

### happy happy joy joy

info_msg "===== build complete" 
info_msg "##### done setting up openresty/nginx + push-stream module. #####"
exit 0
